### ISSUE TITLE
Uncaught Error: Call to a member function getResponseBody() on null

### ISSUE THREAD

**Issue by intelligence** [smtp2go-oss/wordpress-plugin#34]
Trying out this plugin on a staging site I was struck with `There has been a critical error on this website.` when trying to send a test mail from the dashboard. When checking the debug.log, this message is present:
```
[07-Apr-2022 20:56:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getResponseBody() on null in /sites/domain.tld/files/releases/20220407225326/web/app/plugins/smtp2go/smtp2go/WordpressPluginAdmin.php:474
Stack trace:
#0 /sites/domain.tld/files/releases/20220407225326/web/wp/wp-includes/class-wp-hook.php(307): SMTP2GO\WordpressPluginAdmin->sendTestEmail()
#1 /sites/domain.tld/files/releases/20220407225326/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /sites/domain.tld/files/releases/20220407225326/web/wp/wp-includes/plugin.php(474): WP_Hook->do_action()
#3 /sites/domain.tld/files/releases/20220407225326/web/wp/wp-admin/admin-ajax.php(187): do_action()
#4 {main}
  thrown in /sites/domain.tld/files/releases/20220407225326/web/app/plugins/smtp2go/smtp2go/WordpressPluginAdmin.php on line 474
```

Any idea what it could be? I'm on PHP 8, could that be an issue here?

**Comment by markcollister** [comment]
Nice thanks
